Fix FCGI input stream - use cgi.stdinput instead of cgi.in
The FCGI gem's CGI object uses 'stdinput' not 'in' for the input stream.
Using cgi.in caused NoMethodError in production FastCGI environments.

Error was: undefined method 'in' for CGI object at index.fcgi:65